Add open maps
Aouta91/yachtEngineHandler pull request #10
Opened 2020-11-01 01:53 UTC by Aouta91

- add OpenMap
- bit of format index.html

2020-11-01 09:35 UTC, otherman16 requested changes
1. Все `.css` и `.js` лучше скачать и положить в папку static. Отдавать с нашего сервера. Вдруг интернета не будет.
2. Убрать лишний `title`
3. `script` должны быть в конце документа
4. Написанные скрипты и стили нужно вынести в специально созданные для этого `static/yacht.css` и `static/yach.js`

2020-11-01 09:35 UTC, otherman16 commented on index.html
> +        href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css" type="text/css">
Я бы скачал и сохранил `ol.css` в папку `static`, как все остальные css, чтобы не зависеть от наличия интернета.

2020-11-01 09:35 UTC, otherman16 commented on index.html
> +    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/build/ol.js"></script>
Перенести `<script>` к остальным в самый низ документа.
Тоже для случая отсутствия интернета скачать `ol.js` и положить в папку `static`.

2020-11-01 09:35 UTC, otherman16 commented on index.html
> +    <title>OpenLayers example</title>
`<title>` уже есть. И он `Yacht`. Смотри выше.

2020-11-01 09:35 UTC, otherman16 commented on index.html
> +                        </script>
Либо перенести `<script>` к остальным в самый низ документа.
Либо перенести код скрипта в файл `static/yacht.js`. (По моему мнению, этот вариант предпочтительней).

2020-11-01 09:35 UTC, otherman16 commented on index.html
> +                    <div class="row">
Обернуть `<map>` в еще один `<div class="col"></div>`. Это необходимо для унификации сетки бутстрапа.

2020-11-01 09:35 UTC, otherman16 commented on index.html
> +    </style>
Перенести все стили в файл `static/yacht.css`.

2020-11-02 19:30 UTC, otherman16 commented
Как дела? Нужна помощь?

2020-11-06 21:27 UTC, Aouta91 commented on index.html
> +        href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css" type="text/css">
Этот скрипт должен исполняться в header

2020-11-06 21:27 UTC, Aouta91 commented on index.html
> +    <title>OpenLayers example</title>
убрал

2020-11-06 21:31 UTC, Aouta91 commented on index.html
> +                    <div class="row">
обернул. Надо рассмотреть возможность рендеринга html фрагментов с помощью HTML для лучшей масштабируемости

2020-11-06 23:29 UTC, Aouta91 commented on index.html
> +    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/build/ol.js"></script>
этот скрипт лучше остаивиьт  в хеаде . В конце файла он не работает

2020-11-06 23:30 UTC, Aouta91 commented on index.html
> +    </style>
перенесено

2020-11-08 09:43 UTC, otherman16 approved these changes
1. Что за файл ` staff/Schema.bmp ` ?
2. `<script>` внутри map нельзя перенести?
Я аппрувлю, но если вдруг в вышеизложенном есть мотивация к исправлению, то действуй. Если нет, сливай.

2020-11-08 09:43 UTC, otherman16 commented on index.html
> +                            </script>
Нельзя перенести в static/yacht.js ?

2020-11-08 11:08 UTC, iolkhovsky approved these changes

2020-11-08 12:15 UTC, Aouta91 commented on index.html
> +                            </script>
Давай в след итерацию

2020-11-08 12:15 UTC, merged