BoatHardware fixes
Aouta91/yachtEngineHandler pull request #11
Opened 2020-11-06 10:57 UTC by bachev93

Покрыл тестами класс BoatHardware, написал геттеры через property

2020-11-06 15:30 UTC, otherman16 requested changes
1. Классно, что получилось обойтись без абстрактных фабрик.
2. [logging.basicConfig()](https://docs.python.org/3/library/logging.html#logging.basicConfig)
3. Получение инкапсулированного параметра pin_number - это точно необходимо? По-моему снаружи нам не важны номера пинов. Для отдачи на телеметрию важно просто кодовое название "левый двигатель", "светодиод на корме" и т.п. Если я не уловил какой-то нюанс, то сорян, готов выслушать.
4. Для [setter/getter посмотри стандартные возможности python](https://docs.python.org/3/library/functions.html?highlight=property#property). Это очень удобно. Но это на будущее. Сейчас можно пока забить.

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/boat_hardware.py
> +logger.setLevel(logging.DEBUG)
Если я не прав, коллеги поправят, потому что я не уверен.
Не надо в каждом файле устанавливать level и другие параметры logging.
Достаточно в одном (например, главном) вызвать метод [logging.basicConfig(level=..., format=..., ...)](https://docs.python.org/3/library/logging.html#logging.basicConfig).

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/boat_hardware.py
>              speed = 0
А может пусть скорость остается прежней, а не 0, если вдруг подали неверное значение?

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/boat_hardware.py
> +        led_pin: int, номер пина светодиода из конфигурационного файла,
Снаружи нам не нужно знать, какой номер пина у светодиода.
Нам нужна только высокоуровневая информация типа `Светодиод под кодовым именем "Led1" включен`.
Т.е. нужно вернуть словарь вида
```
{
    "Led1": True,
    "Led2": False
}
```

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/boat_hardware.py
> +        pin: int, номер управляющего пина руля из конфигурационного файла,
То же, что и со светододами.

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/boat_hardware.py
> +        pin: int - номер управляющего пина двигателя из конфигурационного файла,
То же, что и со светодиодом. Тут нужно знать left и right движки. Даже в setter-ах ты на вход подаешь не номер пина двигателя, а его кодовое имя left/right.

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/config.py
> +logger.setLevel(logging.DEBUG)
То же, что и в файле boat_hardware.py

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/motor_controller.py
> +logger.setLevel(logging.DEBUG)
То же, что и в файле boat_hardware.py

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/motor_controller.py
> +        pin: int, управляющий пин двигателя
Снаружи нам не важно, какой номер пина этого движка.
Просто вернуть скорость?
Может, я не вижу картины в целом?..

2020-11-06 15:30 UTC, otherman16 commented on raspberryApi/servo.py
> +        pin: int, управляющий пин сервопривода,
То же, что и раньше с номерами пинов.

2020-11-08 11:15 UTC, iolkhovsky approved these changes

2020-11-08 11:15 UTC, iolkhovsky commented on raspberryApi/boat_hardware.py
>              speed = 0
Мне кажется, нужно просто обрезать входное значение реальным диапазоном: 
speed = max(0, min(100, speed))
А ворнинг, что значение пришло кривое, оставить

2020-11-08 11:15 UTC, iolkhovsky commented on raspberryApi/motor_controller.py
> +        pin: int, управляющий пин двигателя
Мне кажется, номер пина для целей контроля не помешает. Но формат возвращаемой структуры я бы сделал более читабельным и очевидным:
{"speed": self._speed, "io_id": self._pin}
Или чето вроде

2020-11-08 13:50 UTC, otherman16 commented
Пацан потонул

2020-11-08 19:44 UTC, closed without merging