Feature/raspberry api
Aouta91/yachtEngineHandler pull request #4
Opened 2020-10-24 21:44 UTC by bachev93

Доделал API для яхты. Управление моторами для лодки будет дописано, когда приедут моторы.

2020-10-25 09:03 UTC, Aouta91 approved these changes

2020-10-25 10:07 UTC, otherman16 requested changes
1. requirements.txt - дополнить своими зависимостями
2. JSONConfig - выполняешь работу, которая уже инкапсулирована внутри. Мой косяк, надо было в docstring написать example использования.
3. loggin - можно минимальными изменениями сделать логирование более удобным и читаемым

2020-10-25 10:07 UTC, otherman16 commented on raspberryApi/config.py
> +import logging
То же самое.
`logger = logging.getLogger(__name__)`
Мой косяк. Сразу не использовал этот метод.
Если остальные одобрят, поменяй тут тоже, плз.

2020-10-25 10:07 UTC, otherman16 commented on requirements.txt
> +pytest
Разве, для твоего кода не нужны какие-то библиотеки?
Дополни, пожалуйста.

2020-10-25 10:16 UTC, bachev93 commented on raspberryApi/config.py
> +import logging
Исправлю этот момент

2020-10-26 19:50 UTC, bachev93 commented
Я услышал все пожелания. Переделаю и заново создам pr

2020-10-26 19:50 UTC, closed without merging